language: node_js
node_js: --lts
script:
- yarn test
cache: yarn
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - yarn test
  - codecov
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - rm ./cc-test-reporter
before_deploy:
  - yarn run build
  - sed -i '/^\/dist\/$/d' .gitignore
deploy:
  provider: heroku
  app: kitten-as-a-service
  api_key: $HEROKU_AUTH_TOKEN
  skip_cleanup: true
  on:
    branch: master
after_deploy:
  - sleep 10
  - curl --fail --silent --show-error https://kitten-as-a-service.herokuapp.com/ >/dev/null || travis_terminate 1
